# Copyright (C) 2016 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
server:
  compression:
    enabled: true
    mime-types: application/hal+json
    min-response-size: 2KB
  error.whitelabel.enabled: false
  # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.webserver.configure-ssl
  http2.enabled: true
  ssl.bundle: microservice
  shutdown: graceful

spring:
  application.name: therapeut
  aop.proxy-target-class: false
  # https://github.com/spring-projects/spring-framework/commit/55b3b28aecdb914224e009c7e53c0d11f0d9cd05
  checkpoint.restore: onRefresh
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data
  datasource:
    url: jdbc:postgresql://postgres/therapeut
    username: therapeut
    password: p
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    locations: classpath:db/migration/{vendor}
    create-schemas: false
    # Tablespace fuer flyway_schema_history
    # MySQL: Flyway generiert bei "CREATE TABLE flyway_schema_history ..." nicht "ROW_FORMAT=COMPACT"
    # Oracle: CREATE TABLESPACE ist sehr kompliziert https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-TABLESPACE.html
    #tablespace: kundespace
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data
  jpa:
    #database-platform: POSTGRESQL
    hibernate:
      # https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl
      #ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      # https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/cfg/AvailableSettings.html
      # https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/cfg/Environment.html
      hibernate:
        #default_schema: kunde
        jdbc:
          time_zone: Europe/Berlin
          batch_versioned_data: true
          # fuer Oracle: der Treiber teilt bei SELECT das Resultat in standardmaessig maximal 10 Datensaetze auf
          #fetch_size: 10
        order_inserts: true
        order_updates: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 20
        xml_mapping_enabled: false
        #mapping.default_list_semantics: LIST
      # https://stackoverflow.com/questions/31585698/spring-boot-jpa2-hibernate-enable-second-level-cache
      # https://jakarta.ee/xml/ns/persistence
      # https://jakarta.ee/xml/ns/persistence/persistence_3_1.xsd
      jakarta.persistence:
        sharedCache.mode: ENABLE_SELECTIVE
        validation.mode: NONE
        # Generierung eines SQL-Skripts mit CREATE TABLE im Wurzelverzeichnis
        # https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl
        #schema-generation.scripts:
        #  action: create
        #  create-target: create.sql
  # siehe org.springframework.boot.autoconfigure.jackson.JacksonProperties
  jackson:
    default-property-inclusion: non_null
    # siehe com.fasterxml.jackson.databind.DeserializationFeature
    deserialization.read-enums-using-to-string: true
    # siehe com.fasterxml.jackson.databind.SerializationFeature
    serialization.write-enums-using-to-string: true
  lifecycle.timeout-per-shutdown-phase: 3s
  mail:
    host: smtp.acme.com
    port: 25
    #protocol: smtp
    properties.mail:
      debug: false
      smtp:
        auth: false
        starttls.enable: false
    # Mailserver des IZ
    #host: smtp.h-ka.de
    #port: 23
    #username: nnvv0011
    #password: blabla
    # GMail
    #host: smtp.gmail.com
    #port: 587
    #properties.mail.smtp.starttls.enable: true
  main.lazy-initialization: true
  mvc.problemdetails.enabled: true
  # fuer Images mit GraalVM Native
  #native.remove-unused-autoconfig: true
  security.user.password: p
  spel.ignore: true
  # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.ssl.jks
  ssl.bundle.jks.microservice:
    key:
      alias: microservice
    keystore:
      location: classpath:keystore.p12
      password: zimmermann
      type: PKCS12
    truststore:
      location: classpath:truststore.p12
      password: zimmermann
      type: PKCS12
  threads.virtual.enabled: true

info.app:
  author: Juergen Zimmermann
  lecture: Softwarearchitektur und Microservices
  semester: 3 und 5
  course: Wirtschaftsinformatik und Informatik

management:
  endpoints.web.exposure.include: "*"
  #endpoint.shutdown.enabled: true
  metrics.tags.application: therapeut
  # Trace every action
  # https://springbootlearning.medium.com/using-micrometer-to-trace-your-spring-boot-app-1fe6ff9982ae
  tracing.sampling.probability: "1.0"

# --------------------------------------------------------
# E i g e n e   P r o p e r t i e s
# --------------------------------------------------------
#app.mail:
#  from: Theo Test <theo@test.de>
#  sales: Maxi Musterfrau <maxi.musterfrau@test.de>

---
# --------------------------------------------------------
# K u b e r n e t e s
# --------------------------------------------------------
# alternativ: azure_app_service, sap, heroku
spring.config.activate.on-cloud-platform: kubernetes
management.endpoint.health:
  enabled: true
  probes.enabled: true
  show-details: ALWAYS
spring.lifecycle.timeout-per-shutdown-phase: 30s

---
# --------------------------------------------------------
# P r o f i l e   " d e v "
# --------------------------------------------------------
spring:
  config.activate.on-profile: dev
  datasource:
    password: p
    # SWA: Einstellungen fuer PostgreSQL, MySQL und Oracle
    url: jdbc:postgresql://localhost/therapeut
    #url: jdbc:mysql://localhost/kunde
    #url: jdbc:oracle:thin:@localhost/FREEPDB1
    username: therapeut

  # SWA: Einstellungen fuer H2
  #  url: jdbc:h2:mem:testdb
  #  username: sa
  #  password: ""
  #h2.console.enabled: true

  # Tablespace fuer flyway_schema_history
  # MySQL: Flyway generiert bei "CREATE TABLE flyway_schema_history ..." nicht "ROW_FORMAT=COMPACT"
  # Oracle: CREATE TABLESPACE ist sehr kompliziert https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/CREATE-TABLESPACE.html
  flyway.tablespace: therapeutspace

  devtools:
    #livereload.enabled: true
    restart:
      #enabled: true
      #poll-interval: 1s
      #quiet-period: 400ms
      trigger-file: .reloadtrigger
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.docker-compose
  # https://stackoverflow.com/questions/76345884/how-to-select-specific-services-of-docker-compose-when-using-spring-boot-docker
  # SWA: "gradle bootRun" mit Artifakt bzw. Modul "org.springframework.boot:spring-boot-docker-compose"
  docker.compose.profiles.active: [postgres]
  #docker.compose.profiles.active: [mysql]
  #docker.compose.profiles.active: [oracle]
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway.clean-disabled: false
  graphql:
    # Pfad fuer GraphiQL: /graphiql
    graphiql.enabled: true
    # Pfad für Schema: /graphql/schema
    schema.printer.enabled: true
  #http.log-request-details: true
  jackson.serialization.indent-output: true
  jpa.properties:
    # https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/cfg/AvailableSettings.html
    # https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/cfg/Environment.html
    hibernate:
      connection.pool_size: 10
      format_sql: true
      highlight_sql: true
      # https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/tool/schema/internal/script/MultiLineSqlScriptExtractor.html
      #hbm2ddl.import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
      use_sql_comments: true
      # Generierung eines SQL-Skripts mit CREATE TABLE im Wurzelverzeichnis
      # https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl
      #jakarta.persistence.schema-generation.scripts:
      #  action: create
      #  create-target: create.sql
  mail:
    host: localhost
    port: 5025
  # https://stackoverflow.com/questions/53723613/how-to-set-enableloggingrequestdetails-true-in-spring-boot#answer-62817587
  mvc.log-request-details: true
  output.ansi.enabled: ALWAYS

management:
  endpoint:
    health:
      enabled: true
      probes.enabled: true
      show-details: ALWAYS
    shutdown.enabled: true
  info.os.enabled: true

server:
  # SWA: auskommentieren, um TLS zu deaktivieren
  #http2.enabled: false
  #ssl.enabled: false
  # SWA: Port 8081 statt 8080
  #port: 8081

  # $env:TEMP\tomcat-docbase.* -> src\main\webapp (urspruengl. fuer WAR)
  # Document Base = Context Root, siehe https://tomcat.apache.org/tomcat-10.1-doc/config/context.html
  # $env:TEMP\hsperfdata_<USERNAME>\<PID> Java HotSpot Performance data log: bei jedem Start der JVM neu angelegt.
  # https://support.oracle.com/knowledge/Middleware/2325910_1.html
  # https://blog.mygraphql.com/zh/notes/java/diagnostic/hsperfdata/hsperfdata
  tomcat.basedir: ./build/tomcat

app:
  password: p
  password-falsch: FALSCH
