### Einen neuen Therapeuten anlegen
GRAPHQL {{graphqlUrl}}

mutation {
  create(
    input: {
      nachname: "Ql"
      vorname: "Graph"
      mitglied_id: "00000000-0000-0000-0000-000000000001"
      email: "graphql@graphql.de"
      geburtsdatum: "2001-01-01"
      geschlecht: WEIBLICH
      adresse: {
        plz: "99999"
        ort: "Graphqlort"
      }
      taetigkeitsbereiche: [PHYSIO, DIAET]
    }
  ) {
    id
  }
}

### Einen neuen Therapeuten mit fehlerhaften Daten anlegen
GRAPHQL {{graphqlUrl}}

mutation {
  create(
    input: {
      vorname: "-.,."
      nachname: "?!:"
      email: "email@"
      geburtsdatum: "2001-01-01"
      geschlecht: WEIBLICH
      adresse: {
        plz: "1234"
        ort: ""
      }
      taetigkeitsbereiche: [PHYSIO, PHYSIO]
    }
  ) {
    id
  }
}

### Einen neuen Therapeut mit existierender Emailadresse anlegen
GRAPHQL {{graphqlUrl}}

mutation {
  create(
    input: {
      nachname: "Graphql"
      vorname: "Graphql"
      email: "admin@acme.com"
      geburtsdatum: "2022-02-01"
      geschlecht: WEIBLICH
      adresse: {
        plz: "99999"
        ort: "Graphqlort"
      }
      taetigkeitsbereiche: [PHYSIO, MASSAGE]
    }
  ) {
    id
  }
}

