### Einen neuen Therapeuten anlegen
POST {{restUrl}}
Content-Type: application/json

< data/therapeut-neu.json


### Einen neuen Therapeuten mit bereits existierender Emailadresse anlegen: 422 (Unprocessable Entity)
POST {{restUrl}}
Content-Type: application/json

< data/therapeut-neu-email-exists.json


