### Einen Therapeuten mittels PUT aktualisieren
PUT {{restUrl}}/00000000-0000-0000-0000-000000000000
If-Match: "0"
Content-Type: application/json

< data/therapeut-30-put.json

### Einen Therapeuten mittels PUT aktualisieren und Email existiert: 422 (Unprocessable Entity)
PUT {{restUrl}}/00000000-0000-0000-0000-000000000001
If-Match: "0"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/therpeut-30-put-email-exists.json

