### Suche mit vorhandener Therapeut-ID
GRAPHQL {{graphqlUrl}}

{
  therapeut(id: "00000000-0000-0000-0000-000000000000") {
    vorname
  }
}

### Suche mit nicht-vorhandener Therapeut-ID
GRAPHQL {{graphqlUrl}}

{
  therapeut(id: "ffffffff-ffff-ffff-ffff-ffffffffffff") {
    nachname
  }
}

### Suche mit vorhandener Therapeut-ID
GRAPHQL {{graphqlUrl}}

{
  therapeut(id: "00000000-0000-0000-0000-000000000001") {
    nachname
    vorname
    email
    geburtsdatum
    geschlecht
    taetigkeitsbereiche
    adresse {
      plz
      ort
    }
  }
}


### Suche alle Therapeuten
GRAPHQL {{graphqlUrl}}

{
  therapeuten {
    id
    nachname
    vorname
    geburtsdatum
    geschlecht
    taetigkeitsbereiche
    adresse {
      plz
      ort
    }
  }
}
