@startuml TherapeutReadService

skinparam classAttributeIconSize 0

package org.springframework.stereotype {
    interface Service
}

package java.util {
    interface Collection<T>
    interface Map<K,V>
    class UUID

    UUID .left[hidden].> Service
}

package com.acme.therapeut {
    package entity {
        class Therapeut << entity >>
        class Mitglied << entity >>


        Therapeut .up[hidden].> Collection
    }

    package repository {
        class TherapeutRepository << control >> << @Repository >>
        class MitgliedRestRepository << control >> << @Repository >>
    }

    package service #DDDDDD {
        class TherapeutReadService << control >> << @Service >> {
            + findById(id: UUID): Therapeut
            + find(queryParams: Map<String, String>): Collection<Therapeut>
            + findByMitgliedId(mitgliedId: UUID): Collection<Therapeut>
            + findMitgliedById(mitgliedId: UUID ): Mitglied
        }

        TherapeutReadService o--> TherapeutRepository : repo
        TherapeutReadService .right.> Therapeut
        TherapeutReadService .up.> Service
        TherapeutReadService .up.> UUID
        TherapeutReadService .up> List
        TherapeutReadService .up.> Map
    }
}

hide empty members

@enduml
